AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  poc-lambda-github-build-trigger

Globals:
  Function:
    Timeout: 3

Resources:
  TriggerBuildFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: poc-lambda-github-build-trigger/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Environment:
        Variables:
          GITHUB_SECRET: null
          GITHUB_OWNER: null
          GITHUB_REPO: null
          EVENT_TYPE: null
      Events:
        TriggerBuild:
          Type: Api
          Properties:
            Path: /trigger
            Method: get

Outputs:
  TriggerBuildAPI:
    Description: "API Gateway endpoint URL for Prod stage for TriggerBuild function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/trigger/"
  TriggerBuildFunction:
    Description: "Trigger Build Lambda Function ARN"
    Value: !GetAtt TriggerBuildFunction.Arn
  TriggerBuildFunctionIamRole:
    Description: "Implicit IAM Role created for Trigger Build function"
    Value: !GetAtt TriggerBuildFunctionRole.Arn
